### ISSUE TITLE
getting num_samples value as 0

### ISSUE THREAD

**Issue by Splinter1080** [haibo-qiu/FROM#10]
Hey I am trying to run the code but I am facing the following error : 

```
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 197, in main
    train_loader = torch.utils.data.DataLoader(
  File "C:\Users\supre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "C:\Users\supre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

Ps ; I tried to `print len(dataset)` , I am getting `0` for that too .

**Comment by haibo-qiu** [comment]
Hi @Splinter1080 ,
The training data is unpacked from the LMDB file using the following class:
https://github.com/haibo-qiu/FROM/blob/416c13c0133a33dbb0dc4aa58bcdb5a76e4f20a3/lib/datasets/dataset.py#L115-L124

If `len(dataset)` is 0, first check if the path to the LMDB file is correct. Then verify that the version of the LMDB package is `lmdb=1.2.0`, as different versions may cause unpacking problems that I have encountered before.

**Comment by haibo-qiu** [comment]
Feel free to reopen this issue if you have any further questions.

**Comment by xhlbetter** [comment]
lmdb=1.2.0 was yanked:
incomplete release

**Comment by xhlbetter** [comment]
So are there any other ways to solve this problem?

**Comment by xhlbetter** [comment]
I would like to ask if you have solved this problem? @Splinter1080
